spring.application.name=barbearia

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# WhatsApp
whatsapp.token=${WHATSAPP_TOKEN}
whatsapp.verify-token=${WHATSAPP_VERIFY_TOKEN}
whatsapp.api-version=v26.0
WHATSAPP_APP_SECRET=${META_APP_SECRET}

whatsapp.notificacao.usar-template=true
whatsapp.notificacao.cliente.usar-template=true

whatsapp.notificacao.intervalo-ms=10000
whatsapp.status.intervalo-ms=5000

# Bloqueio de teste
app.bloqueio-teste.habilitado=false
app.bloqueio-teste.chave=${BLOQUEIO_TESTE_CHAVE}