package com.guilhermelevi.barbearia.domain.enums;

public enum EtapaConversaEnum {

    MENU,
    ESCOLHENDO_SERVICO,
    ESCOLHENDO_DATA,
    ESCOLHENDO_HORARIO,
    CONFIRMANDO,
    CADASTRANDO_SERVICO_NOME,
    CADASTRANDO_SERVICO_PRECO,
    CADASTRANDO_SERVICO_DURACAO,
    CONFIRMANDO_CADASTRO_SERVICO,
    ESCOLHENDO_SERVICO_EDICAO,
    EDITANDO_SERVICO_NOME,
    EDITANDO_SERVICO_PRECO,
    EDITANDO_SERVICO_DURACAO,
    CONFIRMANDO_EDICAO_SERVICO

}
