package com.guilhermelevi.barbearia.service;

import com.guilhermelevi.barbearia.domain.Barbeiro;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

import java.sql.DriverManager;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@EnabledIfEnvironmentVariable(named = "TEST_POSTGRES_URL", matches = ".+")
class ControleRoboPostgresTest {
    @Test
    void atualizaTabelaExistenteComDefaultAtivoEPreservaPausaAposReiniciar() throws Exception {
        String url = System.getenv("TEST_POSTGRES_URL");
        String usuario = System.getenv("TEST_POSTGRES_USERNAME");
        String senha = System.getenv("TEST_POSTGRES_PASSWORD");
        String schema = "teste_robo_" + UUID.randomUUID().toString().replace("-", "");
        try (var conexao = DriverManager.getConnection(url, usuario, senha);
             var sql = conexao.createStatement()) {
            sql.execute("create schema " + schema);
            try {
                sql.execute("create table " + schema + ".barbeiros (id bigint generated by default as identity primary key, nome varchar(255))");
                sql.execute("insert into " + schema + ".barbeiros (nome) values ('Existente')");
                try (var fabrica = fabrica(url, usuario, senha, schema);
                     var sessao = fabrica.openSession()) {
                    var transacao = sessao.beginTransaction();
                    var existente = sessao.find(Barbeiro.class, 1L);
                    assertTrue(existente.isRoboAtivo(), "Cadastro anterior ao deploy deve continuar ativo");
                    existente.setRoboAtivo(false);
                    sessao.persist(Barbeiro.builder().nome("Novo").build());
                    transacao.commit();
                }
                try (var fabrica = fabrica(url, usuario, senha, schema);
                     var sessao = fabrica.openSession()) {
                    assertFalse(sessao.find(Barbeiro.class, 1L).isRoboAtivo(), "Reiniciar não pode reativar o robô");
                    assertTrue(sessao.find(Barbeiro.class, 2L).isRoboAtivo());
                }
                sql.execute("insert into " + schema + ".barbeiros (nome) values ('Sem campo')");
                try (var resultado = sql.executeQuery("select robo_ativo from " + schema + ".barbeiros where nome = 'Sem campo'")) {
                    assertTrue(resultado.next());
                    assertTrue(resultado.getBoolean(1));
                    assertFalse(resultado.wasNull());
                }
            } finally {
                sql.execute("drop schema " + schema + " cascade");
            }
        }
    }

    private SessionFactory fabrica(String url, String usuario, String senha, String schema) {
        return new Configuration().addAnnotatedClass(Barbeiro.class)
                .setProperty("hibernate.connection.url", url)
                .setProperty("hibernate.connection.username", usuario)
                .setProperty("hibernate.connection.password", senha)
                .setProperty("hibernate.default_schema", schema)
                .setProperty("hibernate.hbm2ddl.auto", "update")
                .setProperty("hibernate.hbm2ddl.halt_on_error", "true")
                .buildSessionFactory();
    }
}
